server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Serve static files if they exist, otherwise fallback to index.html
    location / {
        try_files $uri /index.html;
    }

    # Optional: proxy API requests to Django backend
    location /api/ {
        proxy_pass http://krcs_backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    error_page 404 /index.html;
}